version: "3.9"
services:
  web:
    build: .
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
      FIREBASE_PRIVATE_KEY: "${FIREBASE_PRIVATE_KEY}"
      FIREBASE_CLIENT_EMAIL: "${FIREBASE_CLIENT_EMAIL}"
    ports:
      - "80:80"